# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valida < Formula
  desc "CLI Tools to automate API Testing based on OpenAPI Spec"
  homepage "https://github.com/valida-team/valida"
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/valida-team/valida/releases/download/v0.0.6/valida_0.0.6_darwin_amd64.tar.gz"
      sha256 "3070f72162321bfbfd5897432df868b8dec97fd6621435d20fe6f68b490bcf7e"

      def install
        bin.install "valida"
      end
    end
    on_arm do
      url "https://github.com/valida-team/valida/releases/download/v0.0.6/valida_0.0.6_darwin_arm64.tar.gz"
      sha256 "0f3c95adedb72a0c920e2f8c732700b9290ac50e95c2ed562e582ae9de321a63"

      def install
        bin.install "valida"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/valida-team/valida/releases/download/v0.0.6/valida_0.0.6_linux_amd64.tar.gz"
        sha256 "9ccf4dc2c05eb069cf18b09cfd860c4987e60cdec27d47bc0d87415302e485eb"

        def install
          bin.install "valida"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/valida-team/valida/releases/download/v0.0.6/valida_0.0.6_linux_arm64.tar.gz"
        sha256 "88167eb3b98b762881aa04fa431ab645b6ada759b0c1f7f4b8f1a8d4cbf745c8"

        def install
          bin.install "valida"
        end
      end
    end
  end
end
