name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.5
          cache: true
      - run: go mod tidy
      - uses: goreleaser/goreleaser-action@v6.0.0
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
